return {
	{ "projekt0n/github-nvim-theme" },
	{ "GustavoPrietoP/doom-themes.nvim" },
	{ "shaunsingh/nord.nvim" },
	{ "nyoom-engineering/oxocarbon.nvim" },
	{ "morhetz/gruvbox" },
	{ "rebelot/kanagawa.nvim" },
	{ "NLKNguyen/papercolor-theme" },
	{ "Mofiqul/vscode.nvim" },
	{ "nyoom-engineering/oxocarbon.nvim" },
	{ "catppuccin/nvim", name = "catppuccin", priority = 1000 },
	{ "savq/melange-nvim" },
	{ "folke/neodev.nvim" },
	{ "folke/which-key.nvim" },
	{ "williamboman/mason.nvim" },
	{ "williamboman/mason-lspconfig.nvim" },
	{ "neovim/nvim-lspconfig" },
	{ "norcalli/nvim-colorizer.lua", opts = {} },
	{ "echasnovski/mini.nvim", version = false },
	-- { "HiPhish/rainbow-delimiters.nvim" },
}
